[package]
name = "jano-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-subcommand = "0.12"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
